version: '3'

env:
  RELEASE_VERSION: v0.2.2
  RELEASE_COMMENT: "v0.2.2: OpenResponses API"

tasks:
  release-tag:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - git tag -a $RELEASE_VERSION -m "$RELEASE_COMMENT"
      - git push origin $RELEASE_VERSION
