version: '3'

env:
  RELEASE_VERSION: v0.1.0
  RELEASE_COMMENT: "v0.1.0: init release, for debug"

tasks:
  release:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - git tag -a {{ .Version }} -m "{{ .Comment }}"
      - git push origin {{ .Version }}
